nom : Attribution automatique

sur :
  problèmes :
    types : [ouvert]
  pull_request :
    types : [ouvert]

emplois :
  courir :
    fonctionne sur : ubuntu-latest
    autorisations :
      problèmes : écrire
      pull-requests : écriture
    étapes :
      - nom : « Problème d'attribution automatique »
        utilisations : pozil/auto-assign-issue@v1
        avec :
          jeton de dépôt : ${{ secrets.GITHUB_TOKEN }}
          cessionnaires : [milyes, netsecurebot]
          nombre de cessionnaires : 1
